language: node_js
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '6'
- 'node'
sudo: 9000
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
- curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-ffmpeg.sh | sudo bash -
- curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-imagemagick.sh | sudo bash -
- curl -s https://raw.githubusercontent.com/piobyte/flamingo/master/tools/install-graphicsmagick.sh | sudo bash -
install:
- npm install
