language: node_js
cache:
  apt: true
  directories:
  - node_modules
node_js:
- '0.12'
- iojs
before_install:
- curl https://raw.githubusercontent.com/piobyte/flamingo/master/preinstall.sh | sudo bash -
install:
- npm install
